//[{name}, {On field Position}, {off field positon}, {Major}]
const importantPeople = [
    
    ["James Danziger '25", "Prop: 1", "President", "Political Science & Theater"],
    ["Dylan Safai '26", "Hooker: 2", "Rookie", "Political Economy"],
    ["Scottie Bocock '24", "Prop", "Historian", "Economics"],
    ["Simms Berdy '25", "Lock: 4", "Quartermaster", "Chemistry & German"],
    ["Oskar Webster '26", "Lock: 5", "Rookie Liason", "Undecided"],
    ["Zach Bischof '27", "Flanker: 6", "Rookie", "Undecided"],
    ["Michael Pasko '26", "Flanker: 7", "Rookie", "Political Economy"],
    ["Ryan Cass '24", "8-man: 8", "Forwards Captain", "Physics"],
    ["Matt Laws '25", "Scrum Half: 9", "Assistant Captain", "Computer Science"],
    ["Kaan Coffin '26", "Fly Half: 10", "Rookie Liason", "Undecided"],
    ["Puzant Kiwanian '27", "Wing: 11", "Rookie", "Undecided"],
    ["Daniel Davis '24", "Inside Center: 12", "Backs Captain", "Political Science & Philosophy"],
    ["RJ Acosta '26", "Outside Center: 13", "Webmaster", "Economics & Mathematics"],
    ["John Steinmetz '24", "Wing: 14", "Vice-President", "Chinese & Economics"],
    ["Otis Birnbaum '27", "Full Back: 15", "Rookie", "Undecided"],
    ["Elijah Adu '27", "Prop", "Rookie", "Undecided"],
    ["Ronak Dhingra '25", "Lock", "Merchant Tzar", "Computer Science & Economics"],
    ["Arthur Johnson '26", "Flanker", "Chiefton of Protocol", "Statistics & English"],
    ["Charlie Halverson '26", "Wing", "Rookie Liason", "Undecided"],
    ["Evan Boyle '25", "Flanker", "Secretary", "Philosophy"],
    ["Bennett Snyder '25", "Wing", "Cartographer", "Undecided"],
    ["Harris Agha '25", "Inside Center", "Head of Community Service", "Political Science & Art History"],
    ["Henry Whittier '24", "Flanker", "Head of Advice", "Political Economy"],
    ["Wes Morrison '26", "Wing", "Cardio Bunny", "Political Science & History"],
    ["Will Howe '25", "Flanker", "KGB Foreign Spy", "French"],
    ["Will Gallon '25", "Camera Man", "Gym Rat", "Economics"],
    ["Jonathan Patrick '24", "Moral Support", "Alumni Secretary", "Statistics"],
    ["Andrew Boies '25", "Motivational Speaker", "BBC Foreign Correspondent", "Philosophy"],
    ["Owen Patricks '25", "Team Masseur", "Lazy Person", "Chemistry"],
    ]
    
    export default importantPeople;